/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Content": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FirebaseApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseAuthDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseAuthProviderCertUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseAuthUri": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseClientCertUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseClientEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseMessagingSenderId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebasePrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebasePrivateKeyId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseProjectId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseStorageBucket": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseTokenUri": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseType": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseUniverseDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "IdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "Notes": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Uploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "UserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
