openapi: 3.0.3
info:
  title: IPTV
  description: IPTV streaming app
  version: 0.0.1
servers:
  - url: https://khnmi83lig.execute-api.us-east-1.amazonaws.com
  - url: https://ev1133w1ti.execute-api.us-east-1.amazonaws.com
tags:
  - name: Playlist
    description: Playlists for IPTV
  - name: Session
    description: Sessions for IPTV

paths:
  /playlist:
    post:
      tags:
        - Playlist
      summary: Add a new playlist
      description: Add a new playlist
      operationId: addPlaylist
      requestBody:
        description: Create a new playlist
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePlaylist'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Playlist'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - bearerAuth: []
    put:
      tags:
        - Playlist
      summary: Update an existing playlist
      description: Update an existing playlist by Id
      operationId: updatePlaylist
      requestBody:
        description: Update an existent playlist in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePlaylist'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Playlist'
        '400':
          description: Invalid ID supplied
        '404':
          description: Playlist not found
        '422':
          description: Validation exception
      security:
        - bearerAuth: []
    get:
      tags:
        - Playlist
      summary: Finds user's playlists
      description: Find user's playlists
      operationId: getUsersPlaylists
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Playlist'          
      security:
        - bearerAuth: []
        
  /playlist/{playlistId}:
    get:
      tags:
        - Playlist
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPlaylistById
      parameters:
        - name: playlistId
          in: path
          description: ID of a playlist to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Playlist'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Playlist'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
      security:
        - bearerAuth: []
        
    delete:
      tags:
        - Playlist
      summary: Deletes a playlist
      description: delete a playlist
      operationId: deletePlaylist
      parameters:
        - name: api_key
          in: header
          description: ''
          required: false
          schema:
            type: string
        - name: playlistId
          in: path
          description: Playlist id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid pet value
      security:
        - bearerAuth: []
  /playlist/mac/{macAddress}:
    get:
      tags:
        - Playlist
      summary: Finds user's playlists by mac-address
      description: Find user's playlists by mac-address
      operationId: getUsersPlaylistsByMacAddress
      parameters:
        - name: macAddress
          in: path
          description: mac-address
          example: 00:1A:2B:3C:4D:5E
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Playlist'          
      security:
        - bearerAuth: []

  /session:
    post: 
      tags:
        - Session
      summary: Create a session from web app
      description: Create a session from web app with authenticated user
      operationId: createSession
      requestBody: 
        description: Create a session
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSession'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'          
      security:
        - bearerAuth: []

  /session/code/{code}:
    get:
      tags:
        - Session
      summary: Get a session by code
      description: Get custom token from Firebase admin app on the server by providing a code
      operationId: getCustomToken
      parameters:
        - name: code
          in: path
          description: code of a session to get custom token
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'          
        '500':
          description: Session not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: 
                    type: string
                    example: Session not found
components:
  schemas:
    Playlist:
      required:
        - name
      type: object
      properties:
        id:
          type: string
          example: be014610-c100-11ef-b339-8f6b64d7a69e
        title:
          type: string
          example: Entertainment
        description: 
          type: string
          example: Entertainment playlist
        mac_address:
          type: string
          example: 00:1A:2B:3C:4D:5E
        filename: 
          type: string
          example: example.m3u8
        fileKey: 
          type: string
          example: filekey
        playlistUrl: 
          type: string
          example: https://st2.mediabay.tv/KG_KTRK-Balastan/index.m3u8
        createdAt: 
          type: string
          example: "2024-12-24T08:27:42.698Z"
        updatedAt:
          type: string
          example: "2024-12-24T08:27:42.698Z"
    CreatePlaylist: 
      type: object
      required: 
        - title
      properties: 
        title:
          type: string
          example: Entertainment
        description: 
          type: string
          example: Entertainment playlist
        mac_address:
          type: string
          example: 00:1A:2B:3C:4D:5E
        filename: 
          type: string
          example: example.m3u8
        fileKey: 
          type: string
          example: filekey
        playlistUrl: 
          type: string
          example: https://st2.mediabay.tv/KG_KTRK-Balastan/index.m3u8
    UpdatePlaylist: 
      type: object
      required: 
        - title
      properties: 
        title:
          type: string
          example: Entertainment
        description: 
          type: string
          example: Entertainment playlist
        mac_address:
          type: string
          example: 00:1A:2B:3C:4D:5E
        filename: 
          type: string
          example: example.m3u8
        fileKey: 
          type: string
          example: filekey
        playlistUrl: 
          type: string
          example: https://st2.mediabay.tv/KG_KTRK-Balastan/index.m3u8
    Session:
      type: object
      properties:
        id: 
          type: string
          example: be014610-c100-11ef-b339-8f6b64d7a69e
        userId:
          type: string
          example: be014610-c100-11ef-b339-8f6b64d7asdf
        code: 
          type: string
          example: be014610-c100-11ef-b339-8f6b64d7qwer
        access_token:
          type: string
          example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTc0NzY3NzQ4MCwiZXhwIjoxNzQ3NjgxMDgwLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay1ienpmOUBpcHR2LWVlZjI3LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic3ViIjoiZmlyZWJhc2UtYWRtaW5zZGstYnp6ZjlAaXB0di1lZWYyNy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInVpZCI6IkVoYUJIN1VjdERiVFNYZGhPQjRoWFNVdE9vWjIifQ.BuMssInKd3oblGtUsBF00J14zWnFuEcuYIsJEncWigrj64dolBwmsczEctc8vHemx6kLqlCZN3zdOo_oR4kTyrVDdqB9_tmZYMgHoZ9N62QzxV5cDxfboBEit4bt8HohaT94G5PVVQAD4Kzw8YBwmKEvn7Vc2K37IEftgcEvyKzgvocB51Vs7w_F0np-Qz7RspRUTLlYoBh5ODRwY4V_kVo0Yq3Ae_0Ms-Yz-MfYhFDRrmqRb3GHmuiRLVMQ9OATwICM2VRod4u8BExCmPruEo_BRN3JeafBhuiLujeI1qEFY4yJ8uF3eGY048GKAQuRW_MoAUw-rwuF0kqx3JIThg
        expiresAt:
          type: number
          example: 1747688280
        createdAt: 
          type: string
          example: "2024-12-24T08:27:42.698Z"
        updatedAt:
          type: string
          example: "2024-12-24T08:27:42.698Z"
    CreateSession:
      type: object
      required:
        code: string
      properties: 
        code: 
          type: string
          example: someuniquecode123
    SessionResponse:
      type: object
      properties:
        access_token: 
          type: string
          example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTc0NzY3NzQ4MCwiZXhwIjoxNzQ3NjgxMDgwLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay1ienpmOUBpcHR2LWVlZjI3LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwic3ViIjoiZmlyZWJhc2UtYWRtaW5zZGstYnp6ZjlAaXB0di1lZWYyNy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInVpZCI6IkVoYUJIN1VjdERiVFNYZGhPQjRoWFNVdE9vWjIifQ.BuMssInKd3oblGtUsBF00J14zWnFuEcuYIsJEncWigrj64dolBwmsczEctc8vHemx6kLqlCZN3zdOo_oR4kTyrVDdqB9_tmZYMgHoZ9N62QzxV5cDxfboBEit4bt8HohaT94G5PVVQAD4Kzw8YBwmKEvn7Vc2K37IEftgcEvyKzgvocB51Vs7w_F0np-Qz7RspRUTLlYoBh5ODRwY4V_kVo0Yq3Ae_0Ms-Yz-MfYhFDRrmqRb3GHmuiRLVMQ9OATwICM2VRod4u8BExCmPruEo_BRN3JeafBhuiLujeI1qEFY4yJ8uF3eGY048GKAQuRW_MoAUw-rwuF0kqx3JIThg
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
      
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
